### ISSUE TITLE
Crash when nested @apiParam is defined before the root @apiParam

### ISSUE THREAD

**Issue by ThomasVille** [ThomasVille/apidoc-swagger-3#1]
Given this apiDoc:
```
/**
 * @api {put} /user/:id Update User information
 * @apiName UpdateUser
 * @apiGroup User
 *
 * @apiParam id Users unique ID. Default type should be String.
 * 
 * @apiParam {String} [credentials.username] User's username.
 * @apiParam {String} [credentials.password] User's password.
 * @apiParam {Object} [credentials] User credentials.
 *
 * @apiSuccess {Boolean} success True when the update is successful.
 */
```

This crash happens:
```
/apidoc-swagger-3/apidoc_to_swagger.js:154
            mountPlaces[objectName]['properties'][propertyName] = {
                                   ^

TypeError: Cannot read properties of undefined (reading 'properties')
    at /apidoc-swagger-3/apidoc_to_swagger.js:154:36
    at Array.forEach (<anonymous>)
    at transferApidocParamsToSwaggerBody (/apidoc-swagger-3/apidoc_to_swagger.js:118:18)
    at mountResponseSpecSchema (/apidoc-swagger-3/apidoc_to_swagger.js:297:26)
    at generateResponses (/apidoc-swagger-3/apidoc_to_swagger.js:288:5)
    at generateProps (/apidoc-swagger-3/apidoc_to_swagger.js:176:23)
    at extractPaths (/apidoc-swagger-3/apidoc_to_swagger.js:66:27)
    at Object.toSwagger (/apidoc-swagger-3/apidoc_to_swagger.js:15:21)
    at main (/apidoc-swagger-3/lib.js:47:39)
    at Object.<anonymous> (/apidoc-swagger-3/bin.js:110:1)
```

**Comment by ThomasVille** [comment]
IMO, we should continue crashing but at least put a useful error message.

**Comment by ThomasVille** [comment]
Solved by https://github.com/amanoooo/apidoc-swagger-3/commit/68621898e9810c36c3023f000dec41df983dc8ac.
